### ISSUE TITLE
Setup.sh taking input options while installation.

### ISSUE THREAD

**Issue by kskurian** [ANRGUSC/I3-Core#4]
The script to request for input (Y/N) for the following
1. pull I3-core repo
2. pull the SDK repo
3. install docker
4. install Python and its dependencies

**Comment by Maram-Alalwan** [comment]
Hello,
I have an issue when trying to run (i3_start.sh): (Can't find a suitable configuration file in this directory or any parent). Could you please advice?
Thanks
